parameters:
  isolate.transaction.factory.class: Isolate\Framework\PersistenceContext\Transaction\IsolateFactory
  isolate.context.factory.class: Isolate\Framework\PersistenceContext\Factory

services:
  isolate.transaction.factory:
    class: %isolate.transaction.factory.class%
    public: false
    arguments:
        - '@isolate.unit_of_work.factory'

  isolate.transaction.factory.map:
    class: Isolate\Framework\PersistenceContext\Transaction\FactoryMap

  isolate.context.factory:
    class: %isolate.context.factory.class%
    arguments:
        - '@isolate.transaction.factory'
        - '@isolate.transaction.factory.map'
    public: false

  isolate:
    class: Isolate\Isolate
    arguments:
        - '@isolate.context.factory'
