parameters:
  isolate.unit_of_work.factory.class: Isolate\Framework\UnitOfWork\Factory

services:
  isolate.unit_of_work.entity.definition.collection:
    class: Isolate\Framework\UnitOfWork\Entity\DefinitionCollection
    arguments:
      - [] # replaced by EntityDefinitionCompilerPass
    public: false

  isolate.unit_of_work.factory:
    class: '%isolate.unit_of_work.factory.class%'
    arguments:
      - '@isolate.unit_of_work.entity.definition.collection'
    public: false
